name: Deploy to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: vps-wirawan
        steps:
            - name: Deploy via SSH Script
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  script_stop: true
                  script: |
                      cd /home/wirawan/projects/perpustakaan
                      git pull origin main
                      composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
                      npm ci
                      npm run build
                      php artisan optimize
